apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 732008726294.dkr.ecr.ap-southeast-1.amazonaws.com/simple_bank:ea9edf7a402efb62577a2c91df57db32e4de29fa
        ports:
        - containerPort: 8080